language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t iwasakiryota/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true iwasakiryota/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-northeast-1-078139916226"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
